export enum E2EActionEnum {
  ADD_KEY = 'ADD_KEY',
  LOADING = 'LOADING',
  ERRORMSG = 'ERRORMSG',
  FILE_META = 'FILEMETA',
  CLEARSTORE = 'CLEARSTORE',
  SEND_HASHED = 'SEND_HASHED',
  GETFILEINFO = 'GETFILEINFO',
  READYDOWNLOAD = 'READYDOWNLOAD',
  VERIFYENCRYPTION = 'VERIFYENCRYPTION'
}
